### ISSUE TITLE
Jetson nano support

### ISSUE THREAD

**Issue by SaddamBInSyed** [IIT-PAVIS/Social-Distancing#1]
@pmorerio 
@mayaghaei 
@AleDelB 

thanks for your work.

I have tried on my jetson nano but got very poor fps (0.2)

also, I checked TensorRT_pose  detection giving acceptable fps.

Could you post the sample code regarding how to integrate the existing (openpose) code into tensorRT code on jetson nano.

help appreciated.

**Comment by pmorerio** [comment]
Hi,
currently we are not planning integration with other pose extractors, we are sorry about that. In any  case if you have TensorRT_pose running on you Jetson Nano it should be straightforward to adapt the  script accordingly.  
Best luck  with  you project
