### ISSUE TITLE
Implementation on Jetson Nano

### ISSUE THREAD

**Issue by tanueihorng** [IIT-PAVIS/Social-Distancing#12]
Hi there! Thank you for your wonderful work on this. 
This is what the world needs right now!

Can it supports Jetson Nano if I were to implement it on there ? 
+ Do you mind explain how to install open pose? 

Appreciate your help!

**Comment by mayaghaei** [comment]
Hi @tanueihorng, thanks. Implementing the entire framework o JN requires some engineering, but it is doable. For installing openpose also, we would like to refer you to the [openpose project webpage](https://github.com/CMU-Perceptual-Computing-Lab/openpose). The authors have provided an exhaustive readme to help through the installation process.
