### ISSUE TITLE
Issue with TurboJPEG

### ISSUE THREAD

**Issue by BeardyMan37** [IIT-PAVIS/Social-Distancing#13]
Hello there! I am facing issues trying to run the program. I can show the error log below. Can't seem to find what is the problem.

`python3 social-distancing.py --image_in /home/upm/Desktop/Projects/Social-Distancing/samples/286.jpg --image_out /home/upm/Desktop/Projects/Social-Distancing/samples/286_out.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7
Starting OpenPose Python Wrapper...

Error:
Prototxt file not found: /home/dexmac/openpose/models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():58
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():94
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():106
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():102
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractor.cpp:initializationOnThread():34
- /home/upm/Desktop/Projects/Social-Distancing/openpose/include/openpose/pose/wPoseExtractor.hpp:initializationOnThread():57
- /home/upm/Desktop/Projects/Social-Distancing/openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77
Traceback (most recent call last):
  File "social-distancing.py", line 715, in <module>
    social_distance = SocialDistancing(args)
  File "social-distancing.py", line 254, in __init__
    self.jpeg = TurboJPEG()
  File "/home/upm/.virtualenvs/dl4cv/lib/python3.6/site-packages/turbojpeg.py", line 147, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
  File "/home/upm/.virtualenvs/dl4cv/lib/python3.6/site-packages/turbojpeg.py", line 424, in __find_turbojpeg
    'Unable to locate turbojpeg library automatically. '
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Prototxt file not found: /home/dexmac/openpose/models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():58
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():94
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():106
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():102
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/pose/poseExtractor.cpp:initializationOnThread():34
- /home/upm/Desktop/Projects/Social-Distancing/openpose/include/openpose/pose/wPoseExtractor.hpp:initializationOnThread():57
- /home/upm/Desktop/Projects/Social-Distancing/openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77
- [All threads closed and control returned to main thread]
- /home/upm/Desktop/Projects/Social-Distancing/openpose/src/openpose/utilities/errorAndLog.cpp:checkWorkerErrors():280
- /home/upm/Desktop/Projects/Social-Distancing/openpose/include/openpose/thread/threadManager.hpp:stop():243
- /home/upm/Desktop/Projects/Social-Distancing/openpose/include/openpose/wrapper/wrapper.hpp:stop():455
- /home/upm/Desktop/Projects/Social-Distancing/openpose/include/openpose/wrapper/wrapper.hpp:~WrapperT():282
- [Error occurred in a destructor or in the OpenPose Unity Plugin, so no std::exception has been thrown. Returning with exit status 0]
`

**Comment by tian0124** [comment]
@BeardyMan37 May I know how you solve this issue?

**Comment by tian0124** [comment]
@pmorerio any ideaa?

**Comment by pmorerio** [comment]
Have you tried the suggested fix?

> RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
