### ISSUE TITLE
How do you get the coordinates of the corresponding points between src and dst?

### ISSUE THREAD

**Issue by HenryZhangJianhe** [IIT-PAVIS/Social-Distancing#17]
rationed_hight = im_size[1] * self.vertical_ratio
rationed_width = im_size[0] * self.horizontal_ratio
src = np.array([[0, 0], [0, im_size[1]],
                        [im_size[0], im_size[1]],
                        [im_size[0], 0]])
dst = np.array([[0+rationed_width/2, 0+rationed_hight],
                        [0, im_size[1]], [im_size[0],im_size[1]],
                        [im_size[0]-rationed_width/2, 0+rationed_hight]], np.int32)
![图片](https://user-images.githubusercontent.com/52202915/112481737-48ccab80-8db2-11eb-9f03-5c975a03c3e7.png)
![图片](https://user-images.githubusercontent.com/52202915/112482380-f50e9200-8db2-11eb-948a-1249c03d8107.png)

I do not understand how to get dst points coordinates from your description in paper

**Comment by mayaghaei** [comment]
I do not very well understand your question. you'd like to obtain the trapezoid coordinates in relation to the original rectangular image? If this is the question, I think you need to do some coding yourself to extract that from the (imaginary) trapezoid. Note that we do not actually draw a trapezoid, but we implicitly make use of it to tune the parameters.

**Comment by HenryZhangJianhe** [comment]
![image](https://user-images.githubusercontent.com/52202915/115135310-3f99cc00-a04a-11eb-954c-416f3efbde68.png)
1 Does the  ‘image plane’ mean the ground plane in the image?
2 what does the ‘with metrics' mean? what's the difference between this 'metric' and 's' ?

**Comment by yiming107** [comment]
Hi Henry, to answer your questions: (1) yes. When taking about the homography, it is always referring to the same planar surface from different projections. In our case, the plane is the ground plane. (2) "with metrics" means this homography matrix accounts for the mapping from the pixels to metric units, e.g.  meters. This metric is more related to the intrinsic matrix K. Instead "s" is just the scale factor. Its role is for scaling the metric unit at the calibration time to the one you would like to use. Hope this helps.

**Comment by HenryZhangJianhe** [comment]
> I do not very well understand your question. you'd like to obtain the trapezoid coordinates in relation to the original rectangular image? If this is the question, I think you need to do some coding yourself to extract that from the (imaginary) trapezoid. Note that we do not actually draw a trapezoid, but we implicitly make use of it to tune the parameters.

As you can see from the figure below, the vertex coordinates A' and D' of the trapezoid defined in your code are incorrect. I think the correct coordinates should be A'=[(w-w')/2,h'] , D' = [(w+w')/2, h']. 

![image](https://user-images.githubusercontent.com/52202915/115407363-89d5a580-a222-11eb-82f5-9ace3166be7a.png)

**Comment by mayaghaei** [comment]
Hi @HenryZhangJianhe, thanks for your very close look at the code and the paper. Probably our visualization in the paper made you think that our code is wrong, but the truth is the visualization is only in an abstract way describes how the code works. To probably make it easier for you to understand how the code works, W' cannot be described independently from the original image, hence (0,0) and (image_size[0],0). therefore, our code is the way it is. 
Hope this resolves your doubt.
