### ISSUE TITLE
Custom data

### ISSUE THREAD

**Issue by srika91** [IIT-PAVIS/Social-Distancing#19]
Hello @mayaghaei ,

Awesome and interesting work! This has given a breather for some applications which will otherwise require caliberation 

How do i run this for my custom data. If i understand correctly,In your paper you have mentioned about a tool that you have used to get the ratios visually and this accuracy is closer to the grid search way. Can u also upload the code for the same for us to experiment with? In my situation the dataset size is small to estimate with a grid search.

**Comment by mayaghaei** [comment]
Hello @srika91, thanks for your comment and excuse the late reply.

If I understand your question correctly, you are asking regarding how did we obtain human performance on selecting the best ratio?
we did not choose any tool, we visually created all the possible combinations of ratios for a few frames of each video, showed them to the users, and asked them to select the most realistic one to their opinion. Hope this answers your question.
