### ISSUE TITLE
Performance issue in videos with many people

### ISSUE THREAD

**Issue by bohzio** [IIT-PAVIS/Social-Distancing#2]
Hi, I've tried the previus version of the program on this video [https://www.robots.ox.ac.uk/ActiveVision/Research/Projects/2009bbenfold_headpose/Datasets/TownCentreXVID.avi](url)
with a gtx 1060 6 gb and it can hold 10 fps.
However with the new version it only holds 2-3 fps.
There is a way to obtain about the same fps with the new version?
Thank you

**Comment by dexmac221** [comment]
Hi, i'have a gtx 1060 6gb also, yes, your observation is true. This is due to a better (but more heavy) ellipses overlapping control. Anyway you can try to reduce openpose network size parameter to compensate, or reduce video resolution
Thanks
