### ISSUE TITLE
Questions regarding the source code:

### ISSUE THREAD

**Issue by BradKML** [IIT-PAVIS/Social-Distancing#20]
1. How does the source code predict a person's height? (The paper referenced http://users.umiacs.umd.edu/~yaser/PID691698.pdf as the source)
2. Is it possible to measure two people's distance based on the information of the pose?

Note: Height not measured in https://www.ri.cmu.edu/wp-content/uploads/2019/05/MS_Thesis___Gines_Hidalgo___latest_compressed.pdf

**Comment by pmorerio** [comment]
Hi, thanks for writing

1. The code does not predict person height, rather it uses the height of the skeleton for a **local** estimation of a safe ellipsoid around the person.
2. No it is not, at least not with this approach. In fact the ellipsoid is estimated only **locally**. In any case, the estimate would not be precise if the persons are far apart. You may be interested in a follow up of this work which is going to be presented soon at ICIP 2021 https://ieeexplore.ieee.org/document/9506457, where we estimate metric distances.

**Comment by BradKML** [comment]
Thanks for the response and the newer paper, they do seem to be useful for determining pair distance. It is very intriguing. However, there is one small note I would like to ask: are the distances between torsos based on metric or imperial? If not, how can one extrapolate it based on people's heights (if they are ever used)?

**Comment by pmorerio** [comment]
Hi, 
distances are always metric.
We do not estimate metric lengths for each person, rather we assume them to be - on average - the same, as detailed in Table 2.

**Comment by BradKML** [comment]
Understandable. So are there any other project out there that focuses more on Social Proxmics e.g. pointing direction of Head/Torso/Leg Position?

**Comment by pmorerio** [comment]
Not from our side, at least not at the moment.
Best luck with your projects.
