### ISSUE TITLE
installiation

### ISSUE THREAD

**Issue by rahulsv2000** [IIT-PAVIS/Social-Distancing#4]
hi, I liked your work and have a few doubts on how to install the basics and how to get the program running. I tried the method you had told me but still, need clarification please help, please reply

**Comment by pmorerio** [comment]
Hi, we can try to help. Could you be more precise?

**Comment by rahulsv2000** [comment]
Hi soo I was working on a Windows and when I went to see how to install
openpose it said it didn't have support for python on windows
Soo I tried to build it on Ubuntu which is virtualized in my pc

**Comment by Basavarajingalagi** [comment]
can you pls help on how to install this in google collab

**Comment by lorenzoprincipi** [comment]
@Basavarajingalagi at first create a new folder within Google Drive, let's say 'Social-Distancing' (without apices). Then mount the content of your Google Drive:
```python
from google.colab import drive
drive.mount('/content/gdrive')
```
Later on navigate to the newly created folder:
```
%cd /content/gdrive/My\ Drive/Social-Distancing
```
Finally, clone locally the repository:
```
!git clone https://github.com/IIT-PAVIS/Social-Distancing.git
```

Afterwards you may continue the installation by following what reported [here](https://github.com/IIT-PAVIS/Social-Distancing#Installation-steps)

**Comment by pmorerio** [comment]
Thank you @Prinsodular

**Comment by rahulsv2000** [comment]
Thanks
