### ISSUE TITLE
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON`in CMake and have this Python script in the right folder?

### ISSUE THREAD

**Issue by testchange** [IIT-PAVIS/Social-Distancing#5]
Hi,

Thanks for your contribution. This is really helpful for my local community to practise social distancing. 

While setting up, I am encountering an issue as shown in the title. I have followed the prerequisites by downloading `openpose` (https://github.com/esemeniuc/openpose-docker). I have also ran checks(https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md) to ensure that `openpose` is properly installed by using the following code:

```
# From command line
cd build/examples/tutorial_api_python

# Python 3 (default version)
python3 01_body_from_image.py
```

After running the code, there is no exception showing that the library is missing(see image) 
<img width="383" alt="Screenshot 2020-05-14 at 8 12 17 PM" src="https://user-images.githubusercontent.com/11278735/81933034-468cb300-961f-11ea-8d95-76667b1f67ca.png">

I suspect that there is a missing `pyopenpose.py` file since the error is sourced here `from openpose import pyopenpose as op`.  I just could not find the `pyopenpose.py` file in my `openpose` folder even though I have passed the test(see the image above).

Can you help me out?

**Comment by karahancerenes** [comment]
Hi kitcatkai,

I faced with the same error. You have closed the issue, so could you solve the problem?

**Comment by jacob0811** [comment]
Did you find a solution for this?
