### ISSUE TITLE
Having issue with video

### ISSUE THREAD

**Issue by testchange** [IIT-PAVIS/Social-Distancing#7]
No issue with image output but I am having issue with video output. So I can safely rule out any issue with the pre-requisite installations and environments.

This is the code I ran `python3 social-distancing.py --video enabled --stream_in /test.avi --stream_out ./output/1.avi --horizontal_ratio 0.7 --vertical_ratio 0.7 --openpose_folder /openpose/models/`  

The output is 

```
Starting OpenPose Python Wrapper...
: cannot connect to X server 
```

The file `1.avi` is 0 size which does not make any sense. Care to help?

```
total 0
-rw-r--r-- 1 root root 0 May 20 10:24 1.avi
```

**Comment by mayaghaei** [comment]
according to the error, it seems that the environment you are running the code fails to connect to any GUI environment; are you running the code using ssh?
to fix the issue, you need to make a GUI environment available, or remove restrictions on X server.
Maybe you can try with running `xhost +` ?
