### ISSUE TITLE
Corrupted output video and image error

### ISSUE THREAD

**Issue by bpogorelc** [IIT-PAVIS/Social-Distancing#8]
Hi! First I want to congratulate for this amazing project.
I am using an azure virtual machine with Ubuntu 18.04, Python 3.7.7, Cuda 10.0 and CuDNN 7.6.5. My GPU is Nvidia Tesla V100 PCI-E. 
I managed to build opencv from source for GPU using the tutorial at https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/. What I did differently from the tutorial was that I used the master branch (as suggested of bieng faster) of opencv and opencv_contrib which installed opencv version 4.3dev instead of 4.2 release that was used in that tutorial.
Then I used this opencv's build for building openpose from source, finishing without errors. I also installed turbojpeg using:
sudo apt-get update 
sudo apt-get install libturbojpeg
pip install -U git+git://github.com/lilohuang/PyTurboJPEG.git

I am using this command for processing videos (I processed the videos in samples directory of this repo):
"python social-distancing.py --video enabled --stream_in ./samples/video-example3.mp4 --stream_out ./output/video-example3-out.mp4 --horizontal_ratio 0.7 --vertical_ratio 0.7  --openpose_folder /home/adminvdi/sw/openpose/models/
"
It gives me the following warning:
"OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Starting OpenPose Python Wrapper...
[ WARN:0] global /home/adminvdi/opencv/modules/core/src/matrix_expressions.cpp (1334) assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739
"
and it does show the output video on my screen. But the output video saved as video-example3-out.mp4 cannot be played even with VLC player. I also tried to reformat the output video using the ffmpeg commands but ffmpeg  throws an error "Invalid data found when processing input" and cannot convert it either.

It is also interesting that processing the images using the images from the samples directory of this repo and the command:
"python social-distancing.py --image_in ./samples/286.jpg --image_out ./output/286-out.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7 --openpose_folder /home/adminvdi/sw/openpose/models/
"
does not show nor does save any image at all, and it outputs this error:
"[ERROR:0] global /home/adminvdi/opencv/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:
OpenCV(4.3.0-dev) /home/adminvdi/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): ./input_stream.avi in function 'icvExtractPattern'
Error: Opening video stream or file ./input_stream.avi
"

I would really appreciate your help resolving this issue.

**Comment by mayaghaei** [comment]
have you also tried to change the suffix of the video to be saved, to .avi?

**Comment by bpogorelc** [comment]
Thanks a lot for your help @mayaghaei. I will try it right now and report back

**Comment by bpogorelc** [comment]
Thanks again @mayaghaei . For processing video, changing the output suffix to .avi worked like a charm. I'm still getting the following warning but I guess it is not so important:

"Starting OpenPose Python Wrapper...
[ WARN:0] global /home/adminvdi/opencv/modules/core/src/matrix_expressions.cpp (1334) assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739"

@mayaghaei or anybody, maybe do you know how to resolve the second part of my question, the issue with processing images? I did change from .jpg to .png for the output image just to try the same trick but it didn't work.

**Comment by mayaghaei** [comment]
can you please run the following command instead?
`python3 social-distancing.py --image enabled --video disabled --image_in ./samples/286.jpg --image_out 286-out.jpg --horizontal_ratio 0.7 --vertical_ratio 0.7 --openpose_folder /home/adminvdi/sw/openpose/models/`

**Comment by bpogorelc** [comment]
It worked perfectly, @mayaghaei. Thank you very much!!! Now images and videos get processed without an error.
I am getting this warning for images and videos:

"[ WARN:0] global /home/adminvdi/opencv/modules/core/src/matrix_expressions.cpp (1334) assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: opencv/opencv#16739"

but I guess it's just a warning that openCV might change  processing of multi-channel arrays in the future and can ignore it (for now)
