### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by EstebanExplorer** [IIT-PAVIS/Social-Distancing#9]
Hello  I want to thank you and congratulate you on the project, I can only imagine the great effort and dedication dedicated to the project, this message is to tell you that I was thinking of implementing it in a web application which makes it scalable and technically accessible, however I have a doubt, the license is MIT, but it has the following limitation "The software can be used for any non-commercial application to assess compliance with safe distances", the application has a high consumption of computational resources, which it would have costs. I want to know if to make the application viable I can use it for commercial purposes.

Thank you in advance for the response and your time.

**Comment by pmorerio** [comment]
Sorry, no commercial purposes are allowed as the licences states.
